### ISSUE TITLE
Vague Subprocess Error when running crtest

### ISSUE THREAD

**Issue by ginkoshi** [lmanul/crscripts#2]
`ginko@ginko2:~/chromium/src$ python3 ~/Downloads/crscripts-master/crtest AppListPresenterDelegateHomeLauncherTest
Goma is running.
Looking for test targets... Traceback (most recent call last):
  File "/usr/local/google/home/ginko/Downloads/crscripts-master/crtest", line 61, in <module>
    all_test_targets = find_all_test_targets()
  File "/usr/local/google/home/ginko/Downloads/crscripts-master/crtest", line 32, in find_all_test_targets
    "gn ls  " + util.get_out_dir())).decode("utf-8").split("\n")
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['gn', 'ls', 'out/Default']' returned non-zero exit status 1
`
Additional details:
out/Default does exist
out/Default has compiled before
This is ginko@

**Comment by lmanul** [comment]
Thank you for the report! This is just a case of me not checking enough prerequisites and not giving enough information in logs. I added some checks and more messaging. Could you update your 'crscripts' check out, try again, and let me know if this is now less confusing as to what to do? Closing this, but feel free to let me know if this is still confusing.
